import type {Genre} from './model.js';
import type {V5Profile} from './groove-v5-contract.js';

/**
 * Authored Groove V5 profiles. Automated structural checks
 * pass; listening review against genre references is still pending.
 *
 * Each entry is declarative profile data only: no callbacks, no random functions
 * and no audio references. Validation is owned by `validateV5Profile` in
 * `groove-v5.ts`; construction here follows its rules (sixteenth-grid steps in
 * quarter-step increments, shared ID namespace, one- or two-bar kick/snare spines).
 *
 * Design intent per genre, so the eight differ musically rather than
 * cosmetically at matched tempo and settings:
 * - Jungle: two-bar amen/two-step spine, syncopated second-bar kick, swung hats,
 *   a full live snare-ghost vocabulary and all five gestures.
 * - Liquid DnB: rolling "k11" second bar, dense swung sixteenth hats, restrained
 *   ghosts, no reverse/chop, and musical +7 pitch options only.
 * - Boom Bap: laid-back snare (large dragMs), heavy 8th swing, sparse kick pickup
 *   vocabulary and a low-budget spice policy.
 * - Trap: halftime snare on beat 3, a layered hat ladder, six-repeat bursts
 *   when timing permits, and downward pitch steps.
 * - Two Step Garage: shuffled kick on the "and", signature rim/woodblock
 *   percussion, whole-step hats, reverse+pull spice and a high response weight.
 * - Dubstep: near-empty halftime spine, very sparse pulse, reverse/pitch spice
 *   and a low response weight so endings rarely auto-fill.
 * - Breakcore: chopped displaced spine, 32nd-note detail, chaotic ghosts, all
 *   five gestures, 8-repeat bursts and a short repeat gap.
 * - AmenScience: dense amen science spine with extra snares, the deepest ghost
 *   vocabulary, all five gestures and the highest response weight.
 * - Atmospheric Breakcore: a recognizable two-bar drum opening that admits
 *   fractured detail later in a four- or eight-bar phrase. This is a reference-
 *   informed composition policy, not a transcription of SR20DET.
 */
export const V5_PROFILE_OVERRIDES:Partial<Record<Genre,V5Profile>>={
 jungle:{
  genre:'jungle',
  anchors:[
   {id:'jungle-classic',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.95},
    {bar:0,step:4,role:'snare',gain:.93},
    {bar:0,step:10,role:'kick',gain:.82},
    {bar:0,step:12,role:'snare',gain:.93},
    {bar:1,step:0,role:'kick',gain:.95},
    {bar:1,step:4,role:'snare',gain:.93},
    {bar:1,step:7,role:'kick',gain:.8},
    {bar:1,step:12,role:'snare',gain:.92},
    {bar:1,step:15,role:'snare',gain:.78}]},
   {id:'jungle-roller',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.95},
    {bar:0,step:4,role:'snare',gain:.93},
    {bar:0,step:10,role:'kick',gain:.82},
    {bar:0,step:12,role:'snare',gain:.93},
    {bar:1,step:0,role:'kick',gain:.95},
    {bar:1,step:4,role:'snare',gain:.93},
    {bar:1,step:6,role:'kick',gain:.8},
    {bar:1,step:12,role:'snare',gain:.92},
    {bar:1,step:14,role:'snare',gain:.76}]}
  ],
  layers:[
   {id:'jungle-pulse-hat',role:'hat',minimum:0,notes:[
    {step:0,gain:.26,probability:.95},
    {step:2,gain:.28,probability:.95},
    {step:4,gain:.26,probability:.95},
    {step:6,gain:.3,probability:.95},
    {step:8,gain:.26,probability:.95},
    {step:10,gain:.28,probability:.95},
    {step:12,gain:.26,probability:.95},
    {step:14,gain:.32,probability:.95}]},
   {id:'jungle-hat-16ths',role:'hat',minimum:.3,notes:[
    {step:1,gain:.2,probability:.85,syncopated:true},
    {step:3,gain:.21,probability:.85,syncopated:true},
    {step:5,gain:.2,probability:.85,syncopated:true},
    {step:7,gain:.22,probability:.85,syncopated:true},
    {step:9,gain:.2,probability:.85,syncopated:true},
    {step:11,gain:.21,probability:.85,syncopated:true},
    {step:13,gain:.2,probability:.85,syncopated:true},
    {step:15,gain:.22,probability:.85,syncopated:true}]},
   {id:'jungle-hat-32nds',role:'hat',minimum:.9,notes:[
    {step:1.5,gain:.16,probability:.7,syncopated:true},
    {step:3.5,gain:.16,probability:.7,syncopated:true},
    {step:5.5,gain:.16,probability:.7,syncopated:true},
    {step:7.5,gain:.17,probability:.7,syncopated:true},
    {step:9.5,gain:.16,probability:.7,syncopated:true},
    {step:11.5,gain:.16,probability:.7,syncopated:true},
    {step:13.5,gain:.16,probability:.7,syncopated:true},
    {step:15.5,gain:.17,probability:.7,syncopated:true}]},
   {id:'jungle-snare-ghosts',role:'snare',minimum:.25,notes:[
    {step:3,gain:.28,probability:.9,ghost:true},
    {step:7,gain:.3,probability:.9,ghost:true},
    {step:11,gain:.29,probability:.9,ghost:true},
    {step:15,gain:.27,probability:.9,ghost:true}]},
   {id:'jungle-snare-shades',role:'snare',minimum:.75,notes:[
    {step:2,gain:.24,probability:.8,ghost:true},
    {step:6,gain:.25,probability:.8,ghost:true},
    {step:10,gain:.24,probability:.8,ghost:true},
    {step:14,gain:.25,probability:.8,ghost:true}]},
   {id:'jungle-kick-pickup',role:'kick',minimum:.4,notes:[
    {step:3,gain:.5,probability:.8,syncopated:true},
    {step:7,gain:.5,probability:.8,syncopated:true},
    {step:11,gain:.52,probability:.8,syncopated:true},
    {step:14,gain:.52,probability:.8,syncopated:true}]},
   {id:'jungle-percussion-rim',role:'percussion',minimum:.35,notes:[
    {step:2,gain:.28,probability:.85},
    {step:5,gain:.3,probability:.85},
    {step:9,gain:.28,probability:.85},
    {step:13,gain:.32,probability:.85}]},
   {id:'jungle-percussion-toys',role:'percussion',minimum:.9,notes:[
    {step:1,gain:.26,probability:.7,syncopated:true},
    {step:7,gain:.27,probability:.7,syncopated:true},
    {step:11,gain:.26,probability:.7,syncopated:true},
    {step:15,gain:.28,probability:.7,syncopated:true}]},
   {id:'jungle-call-snare',role:'snare',minimum:.5,on:['opening','continuation'],notes:[
    {step:6.5,gain:.28,probability:.7,ghost:true}]},
   {id:'jungle-call-perc',role:'percussion',minimum:.5,on:['opening','continuation'],notes:[
    {step:5.5,gain:.3,probability:.7}]},
   {id:'jungle-answer-snare',role:'snare',minimum:.55,on:['response','turnaround'],notes:[
    {step:15.5,gain:.3,probability:.8,ghost:true}]},
   {id:'jungle-answer-perc',role:'percussion',minimum:.6,on:['response','turnaround'],notes:[
    {step:13.5,gain:.32,probability:.8}]}
  ],
  cadences:[
   {id:'jungle-cadence-snare',role:'snare',minimum:.25,notes:[
    {step:12,gain:.3},
    {step:13,gain:.4},
    {step:14,gain:.5},
    {step:15,gain:.62}]},
   {id:'jungle-cadence-perc',role:'percussion',minimum:.5,notes:[
    {step:14,gain:.3},
    {step:15,gain:.36}]}
  ],
  timing:{
   kick:{swing:0,dragMs:0},
   snare:{swing:.5,dragMs:1.5},
   hat:{swing:.72,dragMs:0},
   percussion:{swing:.5,dragMs:-2}},
  spice:{gestures:['roll','chop','reverse','pitch','push'],roles:['snare','hat','percussion'],maxPerBar:3,maxRepeats:4,minRepeatMs:18,pitchSteps:[0,7,12,-12]},
  responseWeight:1
 },
 liquiddnb:{
  genre:'liquiddnb',
  anchors:[
   {id:'liquid-roller',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.94},
    {bar:0,step:4,role:'snare',gain:.9},
    {bar:0,step:10,role:'kick',gain:.8},
    {bar:0,step:12,role:'snare',gain:.9},
    {bar:1,step:0,role:'kick',gain:.94},
    {bar:1,step:4,role:'snare',gain:.9},
    {bar:1,step:11,role:'kick',gain:.78},
    {bar:1,step:12,role:'snare',gain:.9}]},
   {id:'liquid-float',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.94},
    {bar:0,step:4,role:'snare',gain:.9},
    {bar:0,step:10,role:'kick',gain:.8},
    {bar:0,step:12,role:'snare',gain:.9},
    {bar:1,step:0,role:'kick',gain:.94},
    {bar:1,step:4,role:'snare',gain:.9},
    {bar:1,step:10,role:'kick',gain:.78},
    {bar:1,step:12,role:'snare',gain:.9},
    {bar:1,step:14,role:'snare',gain:.72}]}
  ],
  layers:[
   {id:'liquid-pulse-hat',role:'hat',minimum:0,notes:[
    {step:2,gain:.26,probability:.95},
    {step:6,gain:.27,probability:.95},
    {step:10,gain:.26,probability:.95},
    {step:14,gain:.29,probability:.95}]},
   {id:'liquid-hat-16ths',role:'hat',minimum:.3,notes:[
    {step:1,gain:.18,probability:.65,syncopated:true},
    {step:3,gain:.19,probability:.65,syncopated:true},
    {step:5,gain:.18,probability:.65,syncopated:true},
    {step:7,gain:.2,probability:.65,syncopated:true},
    {step:9,gain:.18,probability:.65,syncopated:true},
    {step:11,gain:.19,probability:.65,syncopated:true},
    {step:13,gain:.18,probability:.65,syncopated:true},
    {step:15,gain:.2,probability:.65,syncopated:true}]},
   {id:'liquid-ghost-snare',role:'snare',minimum:.35,notes:[
    {step:3,gain:.24,probability:.8,ghost:true},
    {step:7,gain:.25,probability:.8,ghost:true},
    {step:11,gain:.24,probability:.8,ghost:true},
    {step:15,gain:.22,probability:.8,ghost:true}]},
   {id:'liquid-percussion',role:'percussion',minimum:.42,notes:[
    {step:5,gain:.27,probability:.8},
    {step:13,gain:.29,probability:.8}]},
   {id:'liquid-kick-sub',role:'kick',minimum:.5,notes:[
    {step:14,gain:.5,probability:.6,syncopated:true}]},
   {id:'liquid-call-hat',role:'hat',minimum:.45,on:['opening','continuation'],notes:[
    {step:5.5,gain:.2,probability:.6}]},
   {id:'liquid-answer-perc',role:'percussion',minimum:.6,on:['response','turnaround'],notes:[
    {step:13.5,gain:.3,probability:.7}]},
   {id:'liquid-high-call',role:'hat',minimum:.75,on:['opening','continuation'],notes:[
    {step:4.5,gain:.16}]},
   {id:'liquid-high-answer',role:'percussion',minimum:.9,on:['response','turnaround'],notes:[
    {step:9.5,gain:.2}]}
  ],
  cadences:[
   {id:'liquid-cadence-snare',role:'snare',minimum:.3,notes:[
    {step:13,gain:.3},
    {step:14,gain:.38},
    {step:15,gain:.46}]},
   {id:'liquid-cadence-hat',role:'hat',minimum:.5,notes:[
    {step:12.5,gain:.22},
    {step:14.5,gain:.24},
    {step:15.5,gain:.28}]}
  ],
  timing:{
   kick:{swing:0,dragMs:0},
   snare:{swing:.5,dragMs:1.5},
   hat:{swing:.72,dragMs:0},
   percussion:{swing:.5,dragMs:-1}},
  spice:{gestures:['roll','push','chop'],roles:['snare','hat','percussion'],maxPerBar:2,maxRepeats:3,minRepeatMs:22,pitchSteps:[0,7]},
  responseWeight:.68
 },
 boombap:{
  genre:'boombap',
  anchors:[
   {id:'boombap-swing-a',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.94},
    {bar:0,step:4,role:'snare',gain:.92},
    {bar:0,step:10,role:'kick',gain:.8},
    {bar:0,step:12,role:'snare',gain:.92},
    {bar:1,step:0,role:'kick',gain:.94},
    {bar:1,step:4,role:'snare',gain:.92},
    {bar:1,step:7,role:'kick',gain:.78},
    {bar:1,step:12,role:'snare',gain:.92}]},
   {id:'boombap-swing-b',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.94},
    {bar:0,step:4,role:'snare',gain:.92},
    {bar:0,step:6,role:'kick',gain:.8},
    {bar:0,step:12,role:'snare',gain:.92},
    {bar:1,step:0,role:'kick',gain:.94},
    {bar:1,step:4,role:'snare',gain:.92},
    {bar:1,step:11,role:'kick',gain:.78},
    {bar:1,step:12,role:'snare',gain:.92}]}
  ],
  layers:[
   {id:'boombap-pulse-hat',role:'hat',minimum:0,notes:[
    {step:2,gain:.27,probability:.88},
    {step:6,gain:.28,probability:.88},
    {step:10,gain:.27,probability:.88},
    {step:14,gain:.3,probability:.88}]},
   {id:'boombap-hat-16ths',role:'hat',minimum:.35,notes:[
    {step:3,gain:.2,probability:.6,syncopated:true},
    {step:7,gain:.21,probability:.6,syncopated:true},
    {step:11,gain:.2,probability:.6,syncopated:true},
    {step:15,gain:.22,probability:.6,syncopated:true}]},
   {id:'boombap-ghost-snare',role:'snare',minimum:.3,notes:[
    {step:3,gain:.26,probability:.85,ghost:true},
    {step:7,gain:.28,probability:.85,ghost:true},
    {step:11,gain:.26,probability:.85,ghost:true},
    {step:15,gain:.25,probability:.85,ghost:true}]},
   {id:'boombap-kick-pickup',role:'kick',minimum:.5,notes:[
    {step:14,gain:.5,probability:.6,syncopated:true}]},
   {id:'boombap-percussion',role:'percussion',minimum:.45,notes:[
    {step:7,gain:.28,probability:.7},
    {step:15,gain:.3,probability:.7}]},
   {id:'boombap-call-snare',role:'snare',minimum:.5,on:['opening','continuation'],notes:[
    {step:7,gain:.26,probability:.55,ghost:true}]},
   {id:'boombap-answer-snare',role:'snare',minimum:.6,on:['response','turnaround'],notes:[
    {step:15,gain:.28,probability:.7,ghost:true}]},
   {id:'boombap-high-call',role:'percussion',minimum:.75,on:['opening','continuation'],notes:[
    {step:5,gain:.22}]},
   {id:'boombap-high-answer',role:'hat',minimum:.9,on:['response','turnaround'],notes:[
    {step:13.5,gain:.18}]}
  ],
  cadences:[
   {id:'boombap-cadence-snare',role:'snare',minimum:.3,notes:[
    {step:13,gain:.34},
    {step:15,gain:.5}]},
   {id:'boombap-cadence-perc',role:'percussion',minimum:.55,notes:[
    {step:11,gain:.28},
    {step:14,gain:.32}]}
  ],
  timing:{
   kick:{swing:0,dragMs:0},
   snare:{swing:.5,dragMs:5},
   hat:{swing:.9,dragMs:0},
   percussion:{swing:.8,dragMs:-1}},
  spice:{gestures:['roll','push','pitch'],roles:['snare','percussion'],maxPerBar:2,maxRepeats:3,minRepeatMs:22,pitchSteps:[0,-2]},
  responseWeight:.72
 },
 trap:{
  genre:'trap',
  anchors:[
   {id:'trap-halftime',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.94},
    {bar:0,step:8,role:'snare',gain:.92},
    {bar:1,step:0,role:'kick',gain:.94},
    {bar:1,step:8,role:'snare',gain:.92},
    {bar:1,step:12,role:'snare',gain:.88},
    {bar:1,step:14,role:'kick',gain:.8}]},
   {id:'trap-roll',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.94},
    {bar:0,step:6,role:'kick',gain:.8},
    {bar:0,step:8,role:'snare',gain:.92},
    {bar:1,step:0,role:'kick',gain:.94},
    {bar:1,step:8,role:'snare',gain:.92},
    {bar:1,step:11,role:'kick',gain:.78},
    {bar:1,step:15,role:'snare',gain:.86}]},
   {id:'trap-triplet',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.94},
    {bar:0,step:3,role:'kick',gain:.8},
    {bar:0,step:8,role:'snare',gain:.92},
    {bar:0,step:11,role:'kick',gain:.78},
    {bar:1,step:0,role:'kick',gain:.94},
    {bar:1,step:8,role:'snare',gain:.92},
    {bar:1,step:12,role:'snare',gain:.88}]}
  ],
  layers:[
   {id:'trap-hat-pulse',role:'hat',minimum:0,notes:[
    {step:0,gain:.24,probability:.95},
    {step:2,gain:.24,probability:.95},
    {step:4,gain:.24,probability:.95},
    {step:6,gain:.24,probability:.95},
    {step:8,gain:.24,probability:.95},
    {step:10,gain:.24,probability:.95},
    {step:12,gain:.24,probability:.95},
    {step:14,gain:.25,probability:.95}]},
   {id:'trap-hat-16ths',role:'hat',minimum:.25,notes:[
    {step:1,gain:.2,probability:.85,syncopated:true},
    {step:3,gain:.2,probability:.85,syncopated:true},
    {step:5,gain:.2,probability:.85,syncopated:true},
    {step:7,gain:.21,probability:.85,syncopated:true},
    {step:9,gain:.2,probability:.85,syncopated:true},
    {step:11,gain:.2,probability:.85,syncopated:true},
    {step:13,gain:.2,probability:.85,syncopated:true},
    {step:15,gain:.21,probability:.85,syncopated:true}]},
   {id:'trap-hat-32nds',role:'hat',minimum:.5,notes:[
    {step:1.5,gain:.16,probability:.55,syncopated:true},
    {step:3.5,gain:.16,probability:.55,syncopated:true},
    {step:5.5,gain:.16,probability:.55,syncopated:true},
    {step:7.5,gain:.17,probability:.55,syncopated:true},
    {step:9.5,gain:.16,probability:.55,syncopated:true},
    {step:11.5,gain:.16,probability:.55,syncopated:true},
    {step:13.5,gain:.16,probability:.55,syncopated:true},
    {step:15.5,gain:.17,probability:.55,syncopated:true}]},
   {id:'trap-ghost-snare',role:'snare',minimum:.35,notes:[
    {step:3,gain:.24,probability:.6,ghost:true},
    {step:7,gain:.25,probability:.6,ghost:true},
    {step:11,gain:.24,probability:.6,ghost:true},
    {step:15,gain:.22,probability:.6,ghost:true}]},
   {id:'trap-kick-808',role:'kick',minimum:.4,notes:[
    {step:7,gain:.55,probability:.7,syncopated:true},
    {step:14,gain:.55,probability:.7,syncopated:true}]},
   {id:'trap-percussion',role:'percussion',minimum:.5,notes:[
    {step:5,gain:.28,probability:.6},
    {step:13,gain:.3,probability:.6}]},
   {id:'trap-answer-hat',role:'hat',minimum:.6,on:['response','turnaround'],notes:[
    {step:15.5,gain:.22,probability:.6}]},
   {id:'trap-high-call',role:'hat',minimum:.75,on:['opening','continuation'],notes:[
    {step:6.5,gain:.16}]},
   {id:'trap-high-answer',role:'hat',minimum:.9,on:['response','turnaround'],notes:[
    {step:15.25,gain:.17}]}
  ],
  cadences:[
   {id:'trap-cadence-hat',role:'hat',minimum:.25,notes:[
    {step:12,gain:.2},
    {step:12.5,gain:.22},
    {step:13,gain:.24},
    {step:13.5,gain:.26},
    {step:14,gain:.28},
    {step:14.5,gain:.3},
    {step:15,gain:.32},
    {step:15.5,gain:.36}]},
   {id:'trap-cadence-snare',role:'snare',minimum:.5,notes:[
    {step:14,gain:.34},
    {step:15,gain:.4}]}
  ],
  timing:{
   kick:{swing:0,dragMs:0},
   snare:{swing:.5,dragMs:0},
   hat:{swing:0,dragMs:0},
   percussion:{swing:.3,dragMs:0}},
  spice:{gestures:['roll','pitch','push'],roles:['hat','snare','percussion','kick'],maxPerBar:4,maxRepeats:6,minRepeatMs:20,pitchSteps:[0,-2,-5,-12]},
  responseWeight:.75
 },
 twostepgarage:{
  genre:'twostepgarage',
  anchors:[
   {id:'twostep-shuffle',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.92},
    {bar:0,step:4,role:'snare',gain:.9},
    {bar:0,step:6,role:'kick',gain:.82},
    {bar:0,step:12,role:'snare',gain:.9},
    {bar:1,step:0,role:'kick',gain:.92},
    {bar:1,step:4,role:'snare',gain:.9},
    {bar:1,step:10,role:'kick',gain:.82},
    {bar:1,step:12,role:'snare',gain:.9}]},
   {id:'twostep-lift',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.92},
    {bar:0,step:4,role:'snare',gain:.9},
    {bar:0,step:7,role:'kick',gain:.82},
    {bar:0,step:12,role:'snare',gain:.9},
    {bar:1,step:0,role:'kick',gain:.92},
    {bar:1,step:4,role:'snare',gain:.9},
    {bar:1,step:10,role:'kick',gain:.82},
    {bar:1,step:12,role:'snare',gain:.9}]},
   {id:'twostep-deep',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.92},
    {bar:0,step:3,role:'kick',gain:.82},
    {bar:0,step:4,role:'snare',gain:.9},
    {bar:0,step:12,role:'snare',gain:.9},
    {bar:1,step:0,role:'kick',gain:.92},
    {bar:1,step:4,role:'snare',gain:.9},
    {bar:1,step:10,role:'kick',gain:.82},
    {bar:1,step:12,role:'snare',gain:.9}]}
  ],
  layers:[
   {id:'twostep-hat-shuffle',role:'hat',minimum:0,notes:[
    {step:2,gain:.24,probability:.85},
    {step:6,gain:.25,probability:.85},
    {step:10,gain:.24,probability:.85},
    {step:14,gain:.27,probability:.85}]},
   {id:'twostep-hat-skips',role:'hat',minimum:.3,notes:[
    {step:1,gain:.2,probability:.7,syncopated:true},
    {step:3,gain:.21,probability:.7,syncopated:true},
    {step:5,gain:.2,probability:.7,syncopated:true},
    {step:7,gain:.22,probability:.7,syncopated:true},
    {step:9,gain:.2,probability:.7,syncopated:true},
    {step:11,gain:.21,probability:.7,syncopated:true},
    {step:13,gain:.2,probability:.7,syncopated:true},
    {step:15,gain:.22,probability:.7,syncopated:true}]},
   {id:'twostep-rim',role:'percussion',minimum:.35,notes:[
    {step:3,gain:.3,probability:.8},
    {step:7,gain:.31,probability:.8},
    {step:11,gain:.3,probability:.8},
    {step:15,gain:.32,probability:.8}]},
   {id:'twostep-ghost-snare',role:'snare',minimum:.4,notes:[
    {step:3,gain:.24,probability:.7,ghost:true},
    {step:11,gain:.25,probability:.7,ghost:true}]},
   {id:'twostep-bass-kick',role:'kick',minimum:.5,notes:[
    {step:14,gain:.5,probability:.6,syncopated:true}]},
   {id:'twostep-call-rim',role:'percussion',minimum:.5,on:['opening','continuation'],notes:[
    {step:6.5,gain:.3,probability:.65}]},
   {id:'twostep-answer-rim',role:'percussion',minimum:.6,on:['response','turnaround'],notes:[
    {step:13.5,gain:.32,probability:.7}]},
   {id:'twostep-high-call',role:'hat',minimum:.75,on:['opening','continuation'],notes:[
    {step:5.5,gain:.18}]},
   {id:'twostep-high-answer',role:'percussion',minimum:.9,on:['response','turnaround'],notes:[
    {step:15.5,gain:.22}]}
  ],
  cadences:[
   {id:'twostep-cadence-rim',role:'percussion',minimum:.3,notes:[
    {step:12,gain:.28},
    {step:13.5,gain:.32},
    {step:15,gain:.38}]},
   {id:'twostep-cadence-snare',role:'snare',minimum:.5,notes:[
    {step:14,gain:.32},
    {step:15.5,gain:.4}]}
  ],
  timing:{
   kick:{swing:0,dragMs:0},
   snare:{swing:.6,dragMs:2},
   hat:{swing:.9,dragMs:0},
   percussion:{swing:.85,dragMs:-1}},
  spice:{gestures:['push','roll','reverse'],roles:['snare','hat','percussion'],maxPerBar:3,maxRepeats:3,minRepeatMs:22,pitchSteps:[0,7]},
  responseWeight:.88
 },
 dubstep:{
  genre:'dubstep',
  anchors:[
   {id:'dubstep-bass-a',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.95},
    {bar:0,step:8,role:'snare',gain:.92},
    {bar:1,step:0,role:'kick',gain:.95},
    {bar:1,step:8,role:'snare',gain:.92},
    {bar:1,step:14,role:'kick',gain:.8}]},
   {id:'dubstep-bass-b',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.95},
    {bar:0,step:6,role:'kick',gain:.8},
    {bar:0,step:8,role:'snare',gain:.92},
    {bar:1,step:0,role:'kick',gain:.95},
    {bar:1,step:8,role:'snare',gain:.92}]},
   {id:'dubstep-bass-c',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.95},
    {bar:0,step:8,role:'snare',gain:.92},
    {bar:1,step:0,role:'kick',gain:.95},
    {bar:1,step:3,role:'kick',gain:.8},
    {bar:1,step:8,role:'snare',gain:.92},
    {bar:1,step:12,role:'snare',gain:.86}]}
  ],
  layers:[
   {id:'dubstep-pulse-hat',role:'hat',minimum:0,notes:[
    {step:2,gain:.22,probability:.8},
    {step:6,gain:.23,probability:.8},
    {step:10,gain:.22,probability:.8},
    {step:14,gain:.24,probability:.8}]},
   {id:'dubstep-hat-detail',role:'hat',minimum:.35,notes:[
    {step:7,gain:.2,probability:.65,syncopated:true},
    {step:15,gain:.21,probability:.65,syncopated:true}]},
   {id:'dubstep-percussion',role:'percussion',minimum:.4,notes:[
    {step:3,gain:.28,probability:.7},
    {step:13,gain:.3,probability:.7}]},
   {id:'dubstep-ghost-snare',role:'snare',minimum:.45,notes:[
    {step:15,gain:.26,probability:.7,ghost:true}]},
   {id:'dubstep-kick-sub',role:'kick',minimum:.5,notes:[
    {step:11,gain:.52,probability:.6,syncopated:true}]},
   {id:'dubstep-call-perc',role:'percussion',minimum:.55,on:['opening','continuation'],notes:[
    {step:6,gain:.3,probability:.55}]},
   {id:'dubstep-answer-perc',role:'percussion',minimum:.6,on:['response','turnaround'],notes:[
    {step:14,gain:.3,probability:.65}]},
   {id:'dubstep-high-call',role:'percussion',minimum:.75,on:['opening','continuation'],notes:[
    {step:6.5,gain:.2}]},
   {id:'dubstep-high-answer',role:'hat',minimum:.9,on:['response','turnaround'],notes:[
    {step:15.5,gain:.16}]}
  ],
  cadences:[
   {id:'dubstep-cadence-perc',role:'percussion',minimum:.3,notes:[
    {step:13,gain:.3},
    {step:15,gain:.38}]},
   {id:'dubstep-cadence-snare',role:'snare',minimum:.5,notes:[
    {step:14,gain:.3},
    {step:15,gain:.36}]}
  ],
  timing:{
   kick:{swing:0,dragMs:0},
   snare:{swing:.5,dragMs:3},
   hat:{swing:.8,dragMs:0},
   percussion:{swing:.7,dragMs:-2}},
  spice:{gestures:['roll','push','reverse','pitch'],roles:['snare','percussion'],maxPerBar:2,maxRepeats:3,minRepeatMs:22,pitchSteps:[0,-2,-12]},
  responseWeight:.62
 },
 breakcore:{
  genre:'breakcore',
  anchors:[
   {id:'breakcore-chop-a',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.94},
    {bar:0,step:4,role:'snare',gain:.92},
    {bar:0,step:9,role:'kick',gain:.82},
    {bar:0,step:12,role:'snare',gain:.92},
    {bar:1,step:3,role:'kick',gain:.8},
    {bar:1,step:7,role:'snare',gain:.9},
    {bar:1,step:11,role:'kick',gain:.82},
    {bar:1,step:15,role:'snare',gain:.9}]},
   {id:'breakcore-chop-b',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.94},
    {bar:0,step:4,role:'snare',gain:.92},
    {bar:0,step:9,role:'kick',gain:.82},
    {bar:0,step:12,role:'snare',gain:.92},
    {bar:1,step:0,role:'kick',gain:.94},
    {bar:1,step:4,role:'snare',gain:.92},
    {bar:1,step:6,role:'kick',gain:.8},
    {bar:1,step:11,role:'snare',gain:.9},
    {bar:1,step:15,role:'snare',gain:.88}]},
   {id:'breakcore-chop-c',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.94},
    {bar:0,step:3,role:'kick',gain:.82},
    {bar:0,step:4,role:'snare',gain:.92},
    {bar:0,step:12,role:'snare',gain:.92},
    {bar:1,step:0,role:'kick',gain:.94},
    {bar:1,step:4,role:'snare',gain:.92},
    {bar:1,step:11,role:'kick',gain:.8},
    {bar:1,step:14,role:'snare',gain:.88}]}
  ],
  layers:[
   {id:'breakcore-pulse-hat',role:'hat',minimum:0,notes:[
    {step:0,gain:.24,probability:.9},
    {step:2,gain:.24,probability:.9},
    {step:4,gain:.24,probability:.9},
    {step:6,gain:.24,probability:.9},
    {step:8,gain:.24,probability:.9},
    {step:10,gain:.24,probability:.9},
    {step:12,gain:.24,probability:.9},
    {step:14,gain:.25,probability:.9}]},
   {id:'breakcore-hat-16ths',role:'hat',minimum:.2,notes:[
    {step:1,gain:.2,probability:.85,syncopated:true},
    {step:3,gain:.2,probability:.85,syncopated:true},
    {step:5,gain:.2,probability:.85,syncopated:true},
    {step:7,gain:.21,probability:.85,syncopated:true},
    {step:9,gain:.2,probability:.85,syncopated:true},
    {step:11,gain:.2,probability:.85,syncopated:true},
    {step:13,gain:.2,probability:.85,syncopated:true},
    {step:15,gain:.21,probability:.85,syncopated:true}]},
   {id:'breakcore-hat-32nds',role:'hat',minimum:.45,notes:[
    {step:1.5,gain:.17,probability:.7,syncopated:true},
    {step:3.5,gain:.17,probability:.7,syncopated:true},
    {step:5.5,gain:.17,probability:.7,syncopated:true},
    {step:7.5,gain:.18,probability:.7,syncopated:true},
    {step:9.5,gain:.17,probability:.7,syncopated:true},
    {step:11.5,gain:.17,probability:.7,syncopated:true},
    {step:13.5,gain:.17,probability:.7,syncopated:true},
    {step:15.5,gain:.18,probability:.7,syncopated:true}]},
   {id:'breakcore-snare-chaos',role:'snare',minimum:.3,notes:[
    {step:2.5,gain:.26,probability:.7,ghost:true},
    {step:6.5,gain:.27,probability:.7,ghost:true},
    {step:10.5,gain:.26,probability:.7,ghost:true},
    {step:14.5,gain:.28,probability:.7,ghost:true}]},
   {id:'breakcore-snare-ghosts',role:'snare',minimum:.4,notes:[
    {step:3,gain:.24,probability:.8,ghost:true},
    {step:7,gain:.25,probability:.8,ghost:true},
    {step:11,gain:.24,probability:.8,ghost:true},
    {step:15,gain:.24,probability:.8,ghost:true}]},
   {id:'breakcore-percussion',role:'percussion',minimum:.3,notes:[
    {step:1,gain:.3,probability:.75},
    {step:5,gain:.3,probability:.75},
    {step:13,gain:.32,probability:.75}]},
   {id:'breakcore-kick-sync',role:'kick',minimum:.35,notes:[
    {step:3,gain:.55,probability:.65,syncopated:true},
    {step:14,gain:.55,probability:.65,syncopated:true}]},
   {id:'breakcore-call-snare',role:'snare',minimum:.5,on:['opening','continuation'],notes:[
    {step:7,gain:.28,probability:.6,ghost:true}]},
   {id:'breakcore-answer-snare',role:'snare',minimum:.6,on:['response','turnaround'],notes:[
    {step:15.5,gain:.3,probability:.7,ghost:true}]},
   {id:'breakcore-high-call',role:'percussion',minimum:.75,on:['opening','continuation'],notes:[
    {step:2.5,gain:.22}]},
   {id:'breakcore-high-answer',role:'snare',minimum:.9,on:['response','turnaround'],notes:[
    {step:13.5,gain:.24,ghost:true}]}
  ],
  cadences:[
   {id:'breakcore-cadence-snare',role:'snare',minimum:.2,notes:[
    {step:10,gain:.3},
    {step:11.5,gain:.36},
    {step:13,gain:.42},
    {step:14.5,gain:.48},
    {step:15.5,gain:.56}]},
   {id:'breakcore-cadence-hat',role:'hat',minimum:.4,notes:[
    {step:11.5,gain:.2},
    {step:12.5,gain:.22},
    {step:13.5,gain:.24},
    {step:14.5,gain:.26},
    {step:15.5,gain:.3}]}
  ],
  timing:{
   kick:{swing:0,dragMs:0},
   snare:{swing:.5,dragMs:0},
   hat:{swing:.6,dragMs:0},
   percussion:{swing:.8,dragMs:-2}},
  spice:{gestures:['roll','chop','reverse','pitch','push'],roles:['snare','hat','percussion','kick'],maxPerBar:6,maxRepeats:8,minRepeatMs:16,pitchSteps:[0,7,12,-12,-5]},
  responseWeight:.95
 },
 amenscience:{
  genre:'amenscience',
  anchors:[
   {id:'amenscience-primary',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.95},
    {bar:0,step:4,role:'snare',gain:.93},
    {bar:0,step:6,role:'kick',gain:.82},
    {bar:0,step:10,role:'kick',gain:.82},
    {bar:0,step:12,role:'snare',gain:.93},
    {bar:1,step:0,role:'kick',gain:.95},
    {bar:1,step:4,role:'snare',gain:.93},
    {bar:1,step:10,role:'snare',gain:.86},
    {bar:1,step:14,role:'kick',gain:.82},
    {bar:1,step:15,role:'snare',gain:.84}]},
   {id:'amenscience-shuffle',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.95},
    {bar:0,step:3,role:'kick',gain:.82},
    {bar:0,step:4,role:'snare',gain:.93},
    {bar:0,step:12,role:'snare',gain:.93},
    {bar:1,step:0,role:'kick',gain:.95},
    {bar:1,step:4,role:'snare',gain:.93},
    {bar:1,step:11,role:'snare',gain:.86},
    {bar:1,step:14,role:'kick',gain:.82},
    {bar:1,step:15,role:'snare',gain:.84}]},
   {id:'amenscience-chop',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.95},
    {bar:0,step:4,role:'snare',gain:.93},
    {bar:0,step:9,role:'kick',gain:.82},
    {bar:0,step:12,role:'snare',gain:.93},
    {bar:1,step:3,role:'kick',gain:.82},
    {bar:1,step:7,role:'snare',gain:.9},
    {bar:1,step:11,role:'kick',gain:.82},
    {bar:1,step:15,role:'snare',gain:.9}]}
  ],
  layers:[
   {id:'amenscience-pulse-hat',role:'hat',minimum:0,notes:[
    {step:0,gain:.24,probability:.92},
    {step:2,gain:.24,probability:.92},
    {step:4,gain:.24,probability:.92},
    {step:6,gain:.24,probability:.92},
    {step:8,gain:.24,probability:.92},
    {step:10,gain:.24,probability:.92},
    {step:12,gain:.24,probability:.92},
    {step:14,gain:.25,probability:.92}]},
   {id:'amenscience-hat-16ths',role:'hat',minimum:.2,notes:[
    {step:1,gain:.2,probability:.85,syncopated:true},
    {step:3,gain:.2,probability:.85,syncopated:true},
    {step:5,gain:.2,probability:.85,syncopated:true},
    {step:7,gain:.21,probability:.85,syncopated:true},
    {step:9,gain:.2,probability:.85,syncopated:true},
    {step:11,gain:.2,probability:.85,syncopated:true},
    {step:13,gain:.2,probability:.85,syncopated:true},
    {step:15,gain:.21,probability:.85,syncopated:true}]},
   {id:'amenscience-hat-32nds',role:'hat',minimum:.5,notes:[
    {step:1.5,gain:.16,probability:.65,syncopated:true},
    {step:3.5,gain:.16,probability:.65,syncopated:true},
    {step:5.5,gain:.16,probability:.65,syncopated:true},
    {step:7.5,gain:.17,probability:.65,syncopated:true},
    {step:9.5,gain:.16,probability:.65,syncopated:true},
    {step:11.5,gain:.16,probability:.65,syncopated:true},
    {step:13.5,gain:.16,probability:.65,syncopated:true},
    {step:15.5,gain:.17,probability:.65,syncopated:true}]},
   {id:'amenscience-snare-ghosts',role:'snare',minimum:.3,notes:[
    {step:3,gain:.26,probability:.8,ghost:true},
    {step:7,gain:.27,probability:.8,ghost:true},
    {step:9,gain:.26,probability:.8,ghost:true},
    {step:11,gain:.26,probability:.8,ghost:true},
    {step:15,gain:.25,probability:.8,ghost:true}]},
   {id:'amenscience-snare-shades',role:'snare',minimum:.45,notes:[
    {step:2,gain:.22,probability:.7,ghost:true},
    {step:6,gain:.23,probability:.7,ghost:true},
    {step:10,gain:.22,probability:.7,ghost:true},
    {step:14,gain:.23,probability:.7,ghost:true}]},
   {id:'amenscience-percussion',role:'percussion',minimum:.35,notes:[
    {step:2,gain:.3,probability:.75},
    {step:5,gain:.3,probability:.75},
    {step:13,gain:.32,probability:.75}]},
   {id:'amenscience-kick-sync',role:'kick',minimum:.4,notes:[
    {step:7,gain:.55,probability:.65,syncopated:true},
    {step:14,gain:.55,probability:.65,syncopated:true}]},
   {id:'amenscience-call-snare',role:'snare',minimum:.5,on:['opening','continuation'],notes:[
    {step:6.5,gain:.28,probability:.6,ghost:true}]},
   {id:'amenscience-answer-snare',role:'snare',minimum:.6,on:['response','turnaround'],notes:[
    {step:11.5,gain:.32,probability:.7,ghost:true}]},
   {id:'amenscience-answer-perc',role:'percussion',minimum:.7,on:['response','turnaround'],notes:[
    {step:15.5,gain:.3,probability:.6}]},
   {id:'amenscience-high-call',role:'percussion',minimum:.75,on:['opening','continuation'],notes:[
    {step:7.5,gain:.22}]},
   {id:'amenscience-high-answer',role:'snare',minimum:.9,on:['response','turnaround'],notes:[
    {step:13.5,gain:.24,ghost:true}]}
  ],
  cadences:[
   {id:'amenscience-cadence-snare',role:'snare',minimum:.2,notes:[
    {step:11.5,gain:.3},
    {step:12.5,gain:.36},
    {step:13.5,gain:.42},
    {step:14.5,gain:.5},
    {step:15.5,gain:.58}]},
   {id:'amenscience-cadence-perc',role:'percussion',minimum:.4,notes:[
    {step:11,gain:.28},
    {step:13,gain:.32},
    {step:15,gain:.36}]}
  ],
  timing:{
   kick:{swing:0,dragMs:0},
   snare:{swing:.5,dragMs:1.5},
   hat:{swing:.7,dragMs:0},
   percussion:{swing:.5,dragMs:-2}},
  spice:{gestures:['roll','chop','reverse','pitch','push'],roles:['snare','hat','percussion','kick'],maxPerBar:5,maxRepeats:8,minRepeatMs:16,pitchSteps:[0,7,12,-12,-5]},
  responseWeight:1
 },
 atmosphericbreakcore:{
  genre:'atmosphericbreakcore',
  anchors:[
   {id:'atmospheric-open-break',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.94},{bar:0,step:4,role:'snare',gain:.88},
    {bar:0,step:10,role:'kick',gain:.78},{bar:0,step:12,role:'snare',gain:.9},
    {bar:1,step:0,role:'kick',gain:.93},{bar:1,step:4,role:'snare',gain:.88},
    {bar:1,step:7,role:'kick',gain:.73},{bar:1,step:12,role:'snare',gain:.9}]},
   {id:'atmospheric-cross-break',bars:2,notes:[
    {bar:0,step:0,role:'kick',gain:.94},{bar:0,step:4,role:'snare',gain:.88},
    {bar:0,step:6,role:'kick',gain:.76},{bar:0,step:12,role:'snare',gain:.9},
    {bar:1,step:0,role:'kick',gain:.93},{bar:1,step:4,role:'snare',gain:.88},
    {bar:1,step:10,role:'kick',gain:.76},{bar:1,step:12,role:'snare',gain:.9}]}
  ],
  layers:[
   {id:'atmospheric-hat-pulse',role:'hat',minimum:0,notes:[
    {step:2,gain:.23,probability:.94},{step:6,gain:.26,probability:.94},
    {step:10,gain:.23,probability:.94},{step:14,gain:.27,probability:.94}]},
   {id:'atmospheric-quiet-ghosts',role:'snare',minimum:.3,notes:[
    {step:3,gain:.24,ghost:true,probability:.78},
    {step:11,gain:.24,ghost:true,probability:.78}]},
   {id:'atmospheric-offbeat-hats',role:'hat',minimum:.45,notes:[
    {step:1,gain:.18,probability:.65,syncopated:true},
    {step:7,gain:.19,probability:.65,syncopated:true},
    {step:11,gain:.18,probability:.65,syncopated:true},
    {step:15,gain:.2,probability:.65,syncopated:true}]},
   {id:'atmospheric-break-pickups',role:'kick',minimum:.52,minimumPhraseProgress:.43,notes:[
    {step:3,gain:.51,probability:.7,syncopated:true},
    {step:14,gain:.49,probability:.7,syncopated:true}]},
   {id:'atmospheric-fractured-snare',role:'snare',minimum:.62,minimumPhraseProgress:.57,notes:[
    {step:6.5,gain:.23,ghost:true,probability:.8},
    {step:15.5,gain:.25,ghost:true,probability:.8}]},
   {id:'atmospheric-high-chops',role:'hat',minimum:.78,minimumPhraseProgress:.57,notes:[
    {step:3.5,gain:.16,probability:.7,syncopated:true},
    {step:7.5,gain:.17,probability:.7,syncopated:true},
    {step:11.5,gain:.16,probability:.7,syncopated:true},
    {step:15.5,gain:.18,probability:.7,syncopated:true}]},
   {id:'atmospheric-percussion-answer',role:'percussion',minimum:.5,
    on:['response','turnaround'],notes:[
    {step:5,gain:.25,probability:.72},{step:13,gain:.29,probability:.72}]}
  ],
  cadences:[
   {id:'atmospheric-snare-lift',role:'snare',minimum:.35,notes:[
    {step:11,gain:.27,ghost:true},{step:13,gain:.36,ghost:true},
    {step:14.5,gain:.43},{step:15.5,gain:.54}]}
  ],
  timing:{
   kick:{swing:0,dragMs:0},snare:{swing:.5,dragMs:1},
   hat:{swing:.64,dragMs:0},percussion:{swing:.5,dragMs:-1}},
  spice:{gestures:['roll','chop','push','pitch'],roles:['snare','hat','percussion'],
   maxPerBar:3,maxRepeats:4,minRepeatMs:20,pitchSteps:[0,7,-5,12]},
  spiceMinimumPhraseProgress:.43,
  responseWeight:.72
 }
};
